theme: vertx-howtos-jekyll-theme

url: https://vertx-howtos.github.io/graalvm-native-image-lambda-howto/

asciidoctor:
  attributes:
    source-highlighter: rouge
    rouge-css: style

exclude:
  - LICENSE
  - build*
  - pom.xml
  - settings.gradle.kts
  - target
  - gradle*
  - src
  - Gemfile*
